# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: latest
    - run: pnpm i
    - run: pnpm run build
    - run: echo "------------"
    - run: ls * */*
    - name: Create release
      uses: actions/upload-artifact@v3
      with:
        name: vendetta.js
        path: dist/*.js
